baseURL = "https://zainfathoni.github.io/idgolang/"
languageCode = "id-id"
title = "IDGolang"
theme = "bleak"
publishDir = "docs"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Your subtitle !"
  description = "Everything is awesome !"
  cover = "/images/golang-gopher.jpg"

  # Google analytics
  googleAnalyticsUserID = "UA-xxxxxxxx-x"
  domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "xxxxxxxxx"

  [params.author]
    firstName = "FirstName"
    lastName = "LastName"
    gender = "(fe)?male"
    userName = "username"
    image = "//www.gravatar.com/avatar/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.png"
    website = "http://www.foo.com"
    twitter = "xxxxxxx"
    github = "xxxxxxx"
    facebook = "xxxxxxxxx"
    linkedin = "xxxxxxxxx"
    gplus = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    gravatarHash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"