baseURL = "https://idgolang.netlify.com"
languageCode = "id-id"
title = "IDGolang"
theme = "learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"